# Generated by Django 3.0.7 on 2020-06-24 14:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multipoint', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('osm_id', models.CharField(max_length=120)),
                ('edge_length', models.FloatField()),
                ('bearing', models.FloatField()),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sub_sequence', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='RoadData_snapped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multipoint', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('osm_id', models.CharField(max_length=120)),
                ('edge_length', models.FloatField()),
                ('bearing', models.FloatField()),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sub_sequence', models.IntegerField(default=-1)),
                ('rating', models.FloatField()),
                ('total_potholes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoadPothole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('rating', models.FloatField()),
                ('bearing', models.FloatField()),
            ],
        ),
    ]
