# Generated by Django 3.0.7 on 2020-06-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadMapView', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadpothole_snapped',
            name='total_potholes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
